# -*- coding: utf-8 -*-
"""Data_Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z8K1y-pAmuyx2xMA-hl4dEuTMKVqh42i
"""

import pandas as pd

df = pd.read_csv('/content/Combined_Data_Products.csv')

df.isnull().sum()

df.dropna(inplace=True)

df.duplicated()

df['timestamp'] = df['timestamp'].str.replace('Reviewed in the United States', '')

df.head()

def convert_month_to_number(date_str):
    # Define a mapping of month names to numbers
    month_dict = {
        'January': '01', 'February': '02', 'March': '03', 'April': '04',
        'May': '05', 'June': '06', 'July': '07', 'August': '08',
        'September': '09', 'October': '10', 'November': '11', 'December': '12'
    }

    # Replace month names with corresponding numbers
    for month_name, month_num in month_dict.items():
        date_str = date_str.replace(month_name, month_num)

    # Split the date string by spaces to extract day, month, and year
    parts = date_str.split()
    month = parts[0]  # Month (numerical)
    day = parts[1].replace(',', '')  # Day (remove comma)
    year = parts[2]  # Year

    # Format the date as MM/DD/YYYY
    formatted_date = f'{month}/{day}/{year}'

    return formatted_date

# Apply the conversion function to the timestamp column
df['timestamp'] = df['timestamp'].apply(convert_month_to_number)

df['is_verified'] = df['is_verified'].apply(lambda x: 1 if x==True else 0)
df[df['is_verified']==False]

df.to_csv('Cleaned_Data.csv')